//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InfoConnDBModel", "Calendar_ConnectorSource", "ConnectorSource", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InfoConn.Data.DBML.ConnectorSource), "Calendar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InfoConn.Data.DBML.Calendar), true)]
[assembly: EdmRelationshipAttribute("InfoConnDBModel", "Calendar_Events", "Calendar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InfoConn.Data.DBML.Calendar), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InfoConn.Data.DBML.Event), true)]
[assembly: EdmRelationshipAttribute("InfoConnDBModel", "ConnectorSource_Events", "ConnectorSource", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InfoConn.Data.DBML.ConnectorSource), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InfoConn.Data.DBML.Event), true)]

#endregion

namespace InfoConn.Data.DBML
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InfoConnDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InfoConnDBEntities object using the connection string found in the 'InfoConnDBEntities' section of the application configuration file.
        /// </summary>
        public InfoConnDBEntities() : base("name=InfoConnDBEntities", "InfoConnDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InfoConnDBEntities object.
        /// </summary>
        public InfoConnDBEntities(string connectionString) : base(connectionString, "InfoConnDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InfoConnDBEntities object.
        /// </summary>
        public InfoConnDBEntities(EntityConnection connection) : base(connection, "InfoConnDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConnectorSource> ConnectorSources
        {
            get
            {
                if ((_ConnectorSources == null))
                {
                    _ConnectorSources = base.CreateObjectSet<ConnectorSource>("ConnectorSources");
                }
                return _ConnectorSources;
            }
        }
        private ObjectSet<ConnectorSource> _ConnectorSources;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Calendar> Calendars
        {
            get
            {
                if ((_Calendars == null))
                {
                    _Calendars = base.CreateObjectSet<Calendar>("Calendars");
                }
                return _Calendars;
            }
        }
        private ObjectSet<Calendar> _Calendars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConnectorSources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConnectorSources(ConnectorSource connectorSource)
        {
            base.AddObject("ConnectorSources", connectorSource);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Calendars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalendars(Calendar calendar)
        {
            base.AddObject("Calendars", calendar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoConnDBModel", Name="Calendar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Calendar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Calendar object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="connectorSourceId">Initial value of the ConnectorSourceId property.</param>
        public static Calendar CreateCalendar(global::System.Int32 id, global::System.Int32 connectorSourceId)
        {
            Calendar calendar = new Calendar();
            calendar.Id = id;
            calendar.ConnectorSourceId = connectorSourceId;
            return calendar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CalendarId
        {
            get
            {
                return _CalendarId;
            }
            set
            {
                OnCalendarIdChanging(value);
                ReportPropertyChanging("CalendarId");
                _CalendarId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CalendarId");
                OnCalendarIdChanged();
            }
        }
        private global::System.String _CalendarId;
        partial void OnCalendarIdChanging(global::System.String value);
        partial void OnCalendarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConnectorSourceId
        {
            get
            {
                return _ConnectorSourceId;
            }
            set
            {
                OnConnectorSourceIdChanging(value);
                ReportPropertyChanging("ConnectorSourceId");
                _ConnectorSourceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectorSourceId");
                OnConnectorSourceIdChanged();
            }
        }
        private global::System.Int32 _ConnectorSourceId;
        partial void OnConnectorSourceIdChanging(global::System.Int32 value);
        partial void OnConnectorSourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfoConnDBModel", "Calendar_ConnectorSource", "ConnectorSource")]
        public ConnectorSource ConnectorSource
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectorSource>("InfoConnDBModel.Calendar_ConnectorSource", "ConnectorSource").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectorSource>("InfoConnDBModel.Calendar_ConnectorSource", "ConnectorSource").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConnectorSource> ConnectorSourceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectorSource>("InfoConnDBModel.Calendar_ConnectorSource", "ConnectorSource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConnectorSource>("InfoConnDBModel.Calendar_ConnectorSource", "ConnectorSource", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfoConnDBModel", "Calendar_Events", "Event")]
        public EntityCollection<Event> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("InfoConnDBModel.Calendar_Events", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("InfoConnDBModel.Calendar_Events", "Event", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoConnDBModel", Name="ConnectorSource")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConnectorSource : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConnectorSource object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="connectorSourceType">Initial value of the ConnectorSourceType property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        /// <param name="expiresDate">Initial value of the ExpiresDate property.</param>
        /// <param name="isUpdateRunning">Initial value of the IsUpdateRunning property.</param>
        /// <param name="cacheLastUpdate_Short">Initial value of the CacheLastUpdate_Short property.</param>
        /// <param name="cacheLastUpdate_Medium">Initial value of the CacheLastUpdate_Medium property.</param>
        /// <param name="cacheLastUpdate_Longer">Initial value of the CacheLastUpdate_Longer property.</param>
        /// <param name="doCacheUpdate_Short">Initial value of the DoCacheUpdate_Short property.</param>
        /// <param name="doCacheUpdate_Medium">Initial value of the DoCacheUpdate_Medium property.</param>
        /// <param name="doCacheUpdate_Longer">Initial value of the DoCacheUpdate_Longer property.</param>
        public static ConnectorSource CreateConnectorSource(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 connectorSourceType, global::System.DateTime lastModified, global::System.DateTime expiresDate, global::System.Boolean isUpdateRunning, global::System.DateTime cacheLastUpdate_Short, global::System.DateTime cacheLastUpdate_Medium, global::System.DateTime cacheLastUpdate_Longer, global::System.Boolean doCacheUpdate_Short, global::System.Boolean doCacheUpdate_Medium, global::System.Boolean doCacheUpdate_Longer)
        {
            ConnectorSource connectorSource = new ConnectorSource();
            connectorSource.Id = id;
            connectorSource.UserId = userId;
            connectorSource.ConnectorSourceType = connectorSourceType;
            connectorSource.LastModified = lastModified;
            connectorSource.ExpiresDate = expiresDate;
            connectorSource.IsUpdateRunning = isUpdateRunning;
            connectorSource.CacheLastUpdate_Short = cacheLastUpdate_Short;
            connectorSource.CacheLastUpdate_Medium = cacheLastUpdate_Medium;
            connectorSource.CacheLastUpdate_Longer = cacheLastUpdate_Longer;
            connectorSource.DoCacheUpdate_Short = doCacheUpdate_Short;
            connectorSource.DoCacheUpdate_Medium = doCacheUpdate_Medium;
            connectorSource.DoCacheUpdate_Longer = doCacheUpdate_Longer;
            return connectorSource;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConnectorSourceType
        {
            get
            {
                return _ConnectorSourceType;
            }
            set
            {
                OnConnectorSourceTypeChanging(value);
                ReportPropertyChanging("ConnectorSourceType");
                _ConnectorSourceType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectorSourceType");
                OnConnectorSourceTypeChanged();
            }
        }
        private global::System.Int32 _ConnectorSourceType;
        partial void OnConnectorSourceTypeChanging(global::System.Int32 value);
        partial void OnConnectorSourceTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FeedUrl
        {
            get
            {
                return _FeedUrl;
            }
            set
            {
                OnFeedUrlChanging(value);
                ReportPropertyChanging("FeedUrl");
                _FeedUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FeedUrl");
                OnFeedUrlChanged();
            }
        }
        private global::System.String _FeedUrl;
        partial void OnFeedUrlChanging(global::System.String value);
        partial void OnFeedUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccessToken
        {
            get
            {
                return _AccessToken;
            }
            set
            {
                OnAccessTokenChanging(value);
                ReportPropertyChanging("AccessToken");
                _AccessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccessToken");
                OnAccessTokenChanged();
            }
        }
        private global::System.String _AccessToken;
        partial void OnAccessTokenChanging(global::System.String value);
        partial void OnAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefressToken
        {
            get
            {
                return _RefressToken;
            }
            set
            {
                OnRefressTokenChanging(value);
                ReportPropertyChanging("RefressToken");
                _RefressToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefressToken");
                OnRefressTokenChanged();
            }
        }
        private global::System.String _RefressToken;
        partial void OnRefressTokenChanging(global::System.String value);
        partial void OnRefressTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpiresDate
        {
            get
            {
                return _ExpiresDate;
            }
            set
            {
                OnExpiresDateChanging(value);
                ReportPropertyChanging("ExpiresDate");
                _ExpiresDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpiresDate");
                OnExpiresDateChanged();
            }
        }
        private global::System.DateTime _ExpiresDate;
        partial void OnExpiresDateChanging(global::System.DateTime value);
        partial void OnExpiresDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUpdateRunning
        {
            get
            {
                return _IsUpdateRunning;
            }
            set
            {
                OnIsUpdateRunningChanging(value);
                ReportPropertyChanging("IsUpdateRunning");
                _IsUpdateRunning = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUpdateRunning");
                OnIsUpdateRunningChanged();
            }
        }
        private global::System.Boolean _IsUpdateRunning;
        partial void OnIsUpdateRunningChanging(global::System.Boolean value);
        partial void OnIsUpdateRunningChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CacheLastUpdate_Short
        {
            get
            {
                return _CacheLastUpdate_Short;
            }
            set
            {
                OnCacheLastUpdate_ShortChanging(value);
                ReportPropertyChanging("CacheLastUpdate_Short");
                _CacheLastUpdate_Short = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CacheLastUpdate_Short");
                OnCacheLastUpdate_ShortChanged();
            }
        }
        private global::System.DateTime _CacheLastUpdate_Short;
        partial void OnCacheLastUpdate_ShortChanging(global::System.DateTime value);
        partial void OnCacheLastUpdate_ShortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CacheLastUpdate_Medium
        {
            get
            {
                return _CacheLastUpdate_Medium;
            }
            set
            {
                OnCacheLastUpdate_MediumChanging(value);
                ReportPropertyChanging("CacheLastUpdate_Medium");
                _CacheLastUpdate_Medium = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CacheLastUpdate_Medium");
                OnCacheLastUpdate_MediumChanged();
            }
        }
        private global::System.DateTime _CacheLastUpdate_Medium;
        partial void OnCacheLastUpdate_MediumChanging(global::System.DateTime value);
        partial void OnCacheLastUpdate_MediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CacheLastUpdate_Longer
        {
            get
            {
                return _CacheLastUpdate_Longer;
            }
            set
            {
                OnCacheLastUpdate_LongerChanging(value);
                ReportPropertyChanging("CacheLastUpdate_Longer");
                _CacheLastUpdate_Longer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CacheLastUpdate_Longer");
                OnCacheLastUpdate_LongerChanged();
            }
        }
        private global::System.DateTime _CacheLastUpdate_Longer;
        partial void OnCacheLastUpdate_LongerChanging(global::System.DateTime value);
        partial void OnCacheLastUpdate_LongerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DoCacheUpdate_Short
        {
            get
            {
                return _DoCacheUpdate_Short;
            }
            set
            {
                OnDoCacheUpdate_ShortChanging(value);
                ReportPropertyChanging("DoCacheUpdate_Short");
                _DoCacheUpdate_Short = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoCacheUpdate_Short");
                OnDoCacheUpdate_ShortChanged();
            }
        }
        private global::System.Boolean _DoCacheUpdate_Short;
        partial void OnDoCacheUpdate_ShortChanging(global::System.Boolean value);
        partial void OnDoCacheUpdate_ShortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DoCacheUpdate_Medium
        {
            get
            {
                return _DoCacheUpdate_Medium;
            }
            set
            {
                OnDoCacheUpdate_MediumChanging(value);
                ReportPropertyChanging("DoCacheUpdate_Medium");
                _DoCacheUpdate_Medium = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoCacheUpdate_Medium");
                OnDoCacheUpdate_MediumChanged();
            }
        }
        private global::System.Boolean _DoCacheUpdate_Medium;
        partial void OnDoCacheUpdate_MediumChanging(global::System.Boolean value);
        partial void OnDoCacheUpdate_MediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DoCacheUpdate_Longer
        {
            get
            {
                return _DoCacheUpdate_Longer;
            }
            set
            {
                OnDoCacheUpdate_LongerChanging(value);
                ReportPropertyChanging("DoCacheUpdate_Longer");
                _DoCacheUpdate_Longer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoCacheUpdate_Longer");
                OnDoCacheUpdate_LongerChanged();
            }
        }
        private global::System.Boolean _DoCacheUpdate_Longer;
        partial void OnDoCacheUpdate_LongerChanging(global::System.Boolean value);
        partial void OnDoCacheUpdate_LongerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfoConnDBModel", "Calendar_ConnectorSource", "Calendar")]
        public EntityCollection<Calendar> Calendars
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Calendar>("InfoConnDBModel.Calendar_ConnectorSource", "Calendar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Calendar>("InfoConnDBModel.Calendar_ConnectorSource", "Calendar", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfoConnDBModel", "ConnectorSource_Events", "Event")]
        public EntityCollection<Event> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("InfoConnDBModel.ConnectorSource_Events", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("InfoConnDBModel.ConnectorSource_Events", "Event", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoConnDBModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="connectorSourceId">Initial value of the ConnectorSourceId property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        public static Event CreateEvent(global::System.Int32 id, global::System.Int32 connectorSourceId, global::System.DateTime startDate, global::System.DateTime endDate)
        {
            Event @event = new Event();
            @event.Id = id;
            @event.ConnectorSourceId = connectorSourceId;
            @event.StartDate = startDate;
            @event.EndDate = endDate;
            return @event;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.String _EventId;
        partial void OnEventIdChanging(global::System.String value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConnectorSourceId
        {
            get
            {
                return _ConnectorSourceId;
            }
            set
            {
                OnConnectorSourceIdChanging(value);
                ReportPropertyChanging("ConnectorSourceId");
                _ConnectorSourceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectorSourceId");
                OnConnectorSourceIdChanged();
            }
        }
        private global::System.Int32 _ConnectorSourceId;
        partial void OnConnectorSourceIdChanging(global::System.Int32 value);
        partial void OnConnectorSourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CalendarId
        {
            get
            {
                return _CalendarId;
            }
            set
            {
                OnCalendarIdChanging(value);
                ReportPropertyChanging("CalendarId");
                _CalendarId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CalendarId");
                OnCalendarIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CalendarId;
        partial void OnCalendarIdChanging(Nullable<global::System.Int32> value);
        partial void OnCalendarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UId
        {
            get
            {
                return _UId;
            }
            set
            {
                OnUIdChanging(value);
                ReportPropertyChanging("UId");
                _UId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UId");
                OnUIdChanged();
            }
        }
        private global::System.String _UId;
        partial void OnUIdChanging(global::System.String value);
        partial void OnUIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfoConnDBModel", "Calendar_Events", "Calendar")]
        public Calendar Calendar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calendar>("InfoConnDBModel.Calendar_Events", "Calendar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calendar>("InfoConnDBModel.Calendar_Events", "Calendar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Calendar> CalendarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calendar>("InfoConnDBModel.Calendar_Events", "Calendar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Calendar>("InfoConnDBModel.Calendar_Events", "Calendar", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfoConnDBModel", "ConnectorSource_Events", "ConnectorSource")]
        public ConnectorSource ConnectorSource
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectorSource>("InfoConnDBModel.ConnectorSource_Events", "ConnectorSource").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectorSource>("InfoConnDBModel.ConnectorSource_Events", "ConnectorSource").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConnectorSource> ConnectorSourceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectorSource>("InfoConnDBModel.ConnectorSource_Events", "ConnectorSource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConnectorSource>("InfoConnDBModel.ConnectorSource_Events", "ConnectorSource", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
